// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Unit Converter</title><style>\n\t\t\tbody {\n\t\t\t\tdisplay: flex;\n\t\t\t\tflex-wrap: wrap;\n\t\t\t\tjustify-content: center;\n\t\t\t\talign-content: space-evenly;\n\t\t\t}\n\t\t\tbutton {\n\t\t\t\twidth: 30%;\n\t\t\t\theight: 20%;\n\t\t\t\tmargin: 0 20%;\n\t\t\t\tcursor: pointer;\n\t\t\t\tborder: solid 3px;\n\t\t\t\tborder-radius: 10px;\n\t\t\t\ttext-decoration: none;\n\t\t\t\tcolor: black;\n\t\t\t\tfont-weight: bold;\n\t\t\t\tfont-size: x-large;\n\t\t\t}\n\t\t\th1 {\n\t\t\t\twidth: 100%;\n\t\t\t\ttext-align: center;\n\t\t\t\tfont-weight: bolder;\n\t\t\t\tfont-size: xx-large;\n\t\t\t}\n\t\t</style></head><body><h1>Unit Converter</h1><button type=\"button\" onclick=\"window.location.pathname = &#39;/length&#39;\">Length Converter</button> <button type=\"button\" onclick=\"window.location.pathname = &#39;/weight&#39;\">Weight Converter</button> <button type=\"button\" onclick=\"window.location.pathname = &#39;/temperature&#39;\">Temperature Converter</button></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
